#pragma once
// mayag::app — input events
//
// The closed sum type of everything that can come from the outside world.
// A GPU UI takes richer input than a terminal one: sub-pixel cursor
// positions, pressure, pinch-zoom, high-resolution scroll deltas, IME
// composition. All of it lands here as plain data.
//
// Deliberately platform-neutral: the Win32 / Cocoa / X11 / Wayland / browser
// layers translate INTO this, and nothing above this file knows they exist.

#include "../core/geometry.hpp"

#include <cstdint>
#include <string>
#include <optional>
#include <variant>

namespace mayag {

// ── keyboard ────────────────────────────────────────────────────────────

/// Physical keys we name. Printable characters arrive as `TextEvent` instead,
/// because "which key produced this character" is a layout question the
/// platform already answered.
enum class Key : std::uint16_t {
    unknown = 0,
    // editing
    enter, tab, backspace, del, insert, escape, space,
    // navigation
    left, right, up, down, home, end, page_up, page_down,
    // modifiers (as keys, for chord detection)
    shift, ctrl, alt, super, caps_lock,
    // function
    f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12,
    // letters — named so shortcuts are readable: `key == Key::s`
    a, b, c, d, e, f, g, h, i, j, k, l, m,
    n, o, p, q, r, s, t, u, v, w, x, y, z,
    // digits
    n0, n1, n2, n3, n4, n5, n6, n7, n8, n9,
    // punctuation commonly bound
    minus, equal, bracket_left, bracket_right, backslash,
    semicolon, quote, comma, period, slash, grave,
};

/// Modifier state as a bitmask. `super` is Cmd on macOS, Win on Windows.
struct Mods {
    bool shift = false;
    bool ctrl  = false;
    bool alt   = false;
    bool super = false;

    friend constexpr bool operator==(Mods, Mods) = default;

    /// The platform-correct "primary" accelerator: Cmd on macOS, Ctrl
    /// elsewhere. Writing `m.primary()` instead of `m.ctrl` is the difference
    /// between an app that feels native on macOS and one that does not.
    [[nodiscard]] constexpr bool primary() const noexcept {
#if defined(__APPLE__)
        return super;
#else
        return ctrl;
#endif
    }
    [[nodiscard]] constexpr bool none() const noexcept {
        return !shift && !ctrl && !alt && !super;
    }
};

struct KeyEvent {
    Key  key = Key::unknown;
    Mods mods{};
    bool repeat = false;   ///< generated by key-repeat, not a fresh press
    friend constexpr bool operator==(const KeyEvent&, const KeyEvent&) = default;
};

/// Committed text. Separate from KeyEvent because one keypress can produce
/// zero characters (dead keys), one, or many (IME commit, paste).
struct TextEvent {
    std::string text;
    friend bool operator==(const TextEvent&, const TextEvent&) = default;
};

/// Text being COMPOSED but not yet committed.
///
/// Typing Japanese, Chinese or Korean goes through an input method: the user
/// types `konnichiwa`, the IME shows a growing preedit (k → ko → こん →
/// こんにちは), offers candidates, and only on confirmation does committed
/// text appear. Without this the framework cannot be used in those languages
/// at all — the keystrokes arrive as Latin letters and the composition never
/// happens.
///
/// Preedit is NOT model state. It belongs to the input method until it
/// commits, which is why it arrives as an event carrying the whole current
/// string rather than as incremental edits.
struct ComposeEvent {
    /// The full in-progress string, replacing any previous preedit.
    std::string text;

    /// Byte range within `text` the IME wants highlighted (the clause being
    /// converted). Equal values mean no selection.
    std::uint32_t selection_start = 0;
    std::uint32_t selection_end   = 0;

    /// Where the caret sits within the preedit, in bytes.
    std::uint32_t caret = 0;

    friend bool operator==(const ComposeEvent&, const ComposeEvent&) = default;
};

/// The input method abandoned or finished composition without committing.
struct ComposeEndEvent {
    friend constexpr bool operator==(ComposeEndEvent, ComposeEndEvent) = default;
};

// ── pointer ─────────────────────────────────────────────────────────────

enum class MouseButton : std::uint8_t { left, right, middle, back, forward };

struct MouseMove {
    Vec2 position{};    ///< in logical pixels, origin top-left
    Vec2 delta{};       ///< movement since the last event
    Mods mods{};
    friend constexpr bool operator==(const MouseMove&, const MouseMove&) = default;
};

struct MouseDown {
    Vec2        position{};
    MouseButton button = MouseButton::left;
    Mods        mods{};
    int         click_count = 1;   ///< 2 = double-click, 3 = triple
    friend constexpr bool operator==(const MouseDown&, const MouseDown&) = default;
};

struct MouseUp {
    Vec2        position{};
    MouseButton button = MouseButton::left;
    Mods        mods{};
    friend constexpr bool operator==(const MouseUp&, const MouseUp&) = default;
};

/// Scroll in logical pixels, not "lines" or "clicks". Trackpads produce
/// smooth sub-pixel deltas; wheels produce quantised jumps. Both normalise
/// here so a scroll view does not need to know which it got.
struct ScrollEvent {
    Vec2 delta{};
    Vec2 position{};
    Mods mods{};
    bool momentum = false;   ///< kinetic phase after the finger lifted
    friend constexpr bool operator==(const ScrollEvent&, const ScrollEvent&) = default;
};

// ── window ──────────────────────────────────────────────────────────────

struct ResizeEvent {
    Vec2  size{};            ///< logical size
    float dpi_scale = 1.0f;  ///< physical / logical
    friend constexpr bool operator==(const ResizeEvent&, const ResizeEvent&) = default;
};

struct FocusEvent {
    bool focused = true;
    friend constexpr bool operator==(FocusEvent, FocusEvent) = default;
};

struct CloseRequest {
    friend constexpr bool operator==(CloseRequest, CloseRequest) = default;
};

/// Emitted once per display refresh when an animation is running.
struct FrameEvent {
    double time    = 0.0;   ///< seconds since app start
    double delta   = 0.0;   ///< seconds since the previous frame
    friend constexpr bool operator==(FrameEvent, FrameEvent) = default;
};

// ── the sum ─────────────────────────────────────────────────────────────

using Event = std::variant<
    KeyEvent, TextEvent, ComposeEvent, ComposeEndEvent,
    MouseMove, MouseDown, MouseUp, ScrollEvent,
    ResizeEvent, FocusEvent, CloseRequest, FrameEvent>;

// ── helpers ─────────────────────────────────────────────────────────────

/// `key(ev, Key::s, {.super = true})` — reads like the shortcut it matches.
[[nodiscard]] inline bool key_pressed(const Event& ev, Key k, Mods mods = {}) noexcept {
    const auto* ke = std::get_if<KeyEvent>(&ev);
    return ke != nullptr && ke->key == k && ke->mods == mods;
}

/// Accelerator match using the platform's primary modifier.
[[nodiscard]] inline bool shortcut(const Event& ev, Key k, bool shift = false) noexcept {
    const auto* ke = std::get_if<KeyEvent>(&ev);
    if (ke == nullptr || ke->key != k) return false;
    return ke->mods.primary() && ke->mods.shift == shift && !ke->mods.alt;
}

/// Pointer position for any event that carries one.
[[nodiscard]] inline std::optional<Vec2> event_position(const Event& ev) noexcept {
    if (const auto* p = std::get_if<MouseMove>(&ev))   return p->position;
    if (const auto* p = std::get_if<MouseDown>(&ev))   return p->position;
    if (const auto* p = std::get_if<MouseUp>(&ev))     return p->position;
    if (const auto* p = std::get_if<ScrollEvent>(&ev)) return p->position;
    return std::nullopt;
}

}  // namespace mayag
