#!/usr/bin/env python3
# Compile mayag's GLSL (from shader_source.hpp) to SPIR-V and emit a C++ header
# with the words as uint32 arrays. Run at CMake configure time when glslc is
# present; the generated header is also checked in so a build with no shader
# compiler still works.
import re, sys, subprocess, tempfile, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'include', 'mayag', 'render', 'shader_source.hpp')

def grab(src, name):
    m = re.search(r'%s\s*=\s*R"(\w+)\((.*?)\)\1"' % name, src, re.S)
    if not m:
        sys.exit("could not find " + name)
    return m.group(2)

def compile_stage(glslc, stage, code):
    with tempfile.NamedTemporaryFile('w', suffix='.'+stage, delete=False) as f:
        f.write(code); path = f.name
    spv = path + '.spv'
    subprocess.check_call([glslc, '-O', '-fshader-stage='+stage, path, '-o', spv])
    data = open(spv, 'rb').read()
    os.unlink(path); os.unlink(spv)
    assert len(data) % 4 == 0
    import struct
    return struct.unpack('<%dI' % (len(data)//4), data)

def emit_array(name, words):
    out = ['inline constexpr std::uint32_t %s[] = {' % name]
    for i in range(0, len(words), 8):
        out.append('    ' + ', '.join('0x%08x' % w for w in words[i:i+8]) + ',')
    out.append('};')
    return '\n'.join(out)

def main():
    glslc = sys.argv[1] if len(sys.argv) > 1 else 'glslc'
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        HERE, '..', 'include', 'mayag', 'render', 'spirv_generated.hpp')
    src = open(SRC).read()
    vert = grab(src, 'glsl_vertex')
    frag = grab(src, 'glsl_fragment').replace('// KERNEL_INSERTED_HERE', grab(src, 'glsl_kernel'))
    vw = compile_stage(glslc, 'vert', vert)
    fw = compile_stage(glslc, 'frag', frag)
    header = f"""#pragma once
// GENERATED by tools/embed_spirv.py from render/shader_source.hpp \u2014 do not edit.
//
// mayag compiles its one GLSL shader to SPIR-V at CMake configure time when a
// shader compiler (glslc) is available, and checks the result in so a build
// with no compiler still has a GPU path. The Vulkan backend loads these words
// directly into a VkShaderModule \u2014 no runtime GLSL, no shaderc dependency.

#include <cstdint>

namespace mayag::render::spirv {{

{emit_array('vertex', vw)}

{emit_array('fragment', fw)}

}}  // namespace mayag::render::spirv
"""
    open(out_path, 'w').write(header)
    print(f"wrote {out_path}: vert {len(vw)} words, frag {len(fw)} words")

if __name__ == '__main__':
    main()
